server:
  port: 9001
spring:
  application:
    name: credit-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        # cluster-name: CS

      username: nacos
      password: 123456
